apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: allfiles-staging
  labels:
    app: nginx
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: staging
  template:
    metadata:
      labels:
        app: nginx
        env: staging
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
